name: Build and Upload APK to Repo

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip libncurses6 libstdc++6 libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade buildozer

      - name: Build APK using Buildozer
        run: |
          buildozer android debug | tee buildozer_output.log

      - name: Upload APK as GitHub Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: sriverse-apk
          path: |
            bin/**/*.apk

      - name: Show Build Logs (on failure)
        if: failure()
        run: |
          echo "=== Showing last 100 lines of buildozer_output.log ==="
          tail -n 100 buildozer_output.log || echo "Log file not found"
