name: Build

on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies (Cython, wheel, etc.)
        run: |
          pip install --upgrade cython wheel setuptools

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: ${{ steps.buildozer.outputs.filename }}

      - name: Show Build Logs (on failure)
        if: failure()
        run: |
          echo "=== Showing last 100 lines of buildozer_output.log ==="
          tail -n 100 buildozer_output.log || echo "Log file not found"
