name: Build and Upload APK to Repo

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip libncurses6 libstdc++6 libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade buildozer

      - name: Build APK using Buildozer
        run: |
          buildozer android debug | tee buildozer_output.log

      - name: Find APK path
        id: find_apk
        run: |
          APK_PATH=$(find bin/ -type f -name "*.apk" | head -n 1)
          echo "APK_PATH=$APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "apk=$APK_PATH" >> $GITHUB_OUTPUT
          test -f "$APK_PATH" || (echo "❌ APK not found. Check build logs." && exit 1)

      - name: Push APK to `apk-output` branch
        run: |
          mkdir upload
          cp "$APK_PATH" upload/
          cd upload

          git init
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b apk-output
          git add .
          git commit -m "Upload APK - $(date)"
          git push --force origin apk-output

      - name: Show Build Logs (on failure)
        if: failure()
        run: |
          echo "=== Showing last 100 lines of buildozer_output.log ==="
          tail -n 100 buildozer_output.log || echo "Log file not found"
