name: Build APK

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Preinstall Cython (for .pyx → .c)
        run: pip install cython==0.29.36

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer android debug

      - name: Find and Upload APK
        run: |
          APK_PATH=$(find . -name "*.apk" | head -n 1)
          echo "APK found at: $APK_PATH"
          if [ -f "$APK_PATH" ]; then
            echo "apk_path=$APK_PATH" >> $GITHUB_ENV
          else
            echo "❌ APK not found"
            exit 1
          fi

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: versepad-apk
          path: ${{ env.apk_path }}

      - name: Show Logs on Failure
        if: failure()
        run: |
          echo "🔍 Build failed. Dumping last lines of any build logs:"
          find . -name "*.log" | xargs -r tail -n 50 || echo "No logs found"
