name: Build APK

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Preinstall Cython for native .pyx compilation
        run: |
          pip install cython==0.29.36

      - name: Build APK with Buildozer
        uses: kivy/buildozer-action@v1.0.0
        with:
          command: buildozer android debug

      - name: Upload built APK
        uses: actions/upload-artifact@v4
        with:
          name: versepad-apk
          path: bin/*.apk

      - name: Show Build Logs (on failure)
        if: failure()
        run: |
          echo "🔍 Build failed — showing log"
          find . -name "*.log" | xargs -I{} tail -n 50 {}
