name: Build

on: [push, pull_request]

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable

      - name: Find and Upload APK
        run: |
          APK_PATH=$(find . -name "*.apk" | head -n 1)
          echo "APK found at: $APK_PATH"
          if [ -f "$APK_PATH" ]; then
            echo "Uploading $APK_PATH"
            echo "apk_path=$APK_PATH" >> $GITHUB_ENV
          else
            echo "❌ APK not found"
            exit 1
          fi
      - name: Upload APK
        if: env.apk_path != ''
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: ${{ env.apk_path }}

      - name: Show Build Logs (on failure)
        if: failure()
        run: |
          echo "=== Showing last 100 lines of buildozer_output.log ==="
          tail -n 100 buildozer_output.log || echo "Log file not found"
