name: Build and Upload APK to Repo

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip libncurses6 libstdc++6 libffi-dev libssl-dev

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: stable

      - name: Find built APK path
        id: find_apk
        run: |
          echo "Looking for APK..."
          APK_PATH=$(find . -type f -name "*.apk" | grep bin | head -n 1 || true)
          if [ -z "$APK_PATH" ]; then
            echo "❌ APK not found. Build likely failed."
            exit 1
          fi
          echo "✅ APK found at: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "APK_NAME=$(basename $APK_PATH)" >> $GITHUB_ENV

      - name: Push APK to apk-output branch
        run: |
          mkdir upload
          cp "$APK_PATH" upload/
          cd upload

          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout -b apk-output
          git add .
          git commit -m "Upload APK - $(date)"
          git push --force origin apk-output
        env:
          APK_PATH: ${{ env.APK_PATH }}

      - name: Show tail of Buildozer log on failure
        if: failure()
        run: |
          echo "==== Last 100 lines of Buildozer Log ===="
          tail -n 100 .buildozer/android/platform/build*/dists/*/build/log.txt || true
